[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    titleAddition = "A powerful and cross-platform audio engine, optimized for games"
    description = "Amplitude is a full-featured and cross-platform audio engine designed with the needs of games in mind. With his efficient audio mixer, you have all the controls to play spatialized sounds in 3D environments with custom attenuation models and a lot more."
    footer = 'Copyright Â© Sparky Studios. All Rights Reserved. Licensed under Apache-2.0'
    alertText = '<a class="alert-link stretched-link fw-normal" href="https://studio.amplitudeaudiosdk.com">Amplitude Studio 1.0 just shipped!</a>'
